trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: pip install -r requirements.txt
  displayName: "Install Dependencies"

- script: echo "Running CI Checks"
  displayName: "Run CI Task"
